/* ===== record-shelf 資料檔 =====
   index.html 與 intro.html 共用；這是唯一要編輯的資料來源。
   ALBUMS：新→舊；NOTES：唱片內頁，key 對 ALBUMS 的 id。 */

/* ================= data（新 → 舊）================= */
const ALBUMS = [
  {id:'birds-of-a-feather', title:'BIRDS OF A FEATHER', artist:'Billie Eilish', collab:'',
   date:'May 17', year:'2024', bg:'#263f54', meta:'Single · 3:30',
   q:'Billie Eilish BIRDS OF A FEATHER', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/34/31/d3/3431d34e-847f-5d66-df83-0bce688d997e/mzaf_18106743962423782018.plus.aac.p.m4a'},
  {id:'beautiful-things', title:'Beautiful Things', artist:'Benson Boone', collab:'',
   date:'Jan 18', year:'2024', bg:'#3f3d3c', meta:'Single · 3:00',
   q:'Benson Boone Beautiful Things', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/4d/d5/00/4dd5006f-ee02-c3f1-94db-0ed4b8dd68f1/mzaf_14250561294796027079.plus.aac.p.m4a'},
  {id:'end-of-beginning', title:'End of Beginning', artist:'Djo', collab:'',
   date:'Sep 16', year:'2022', bg:'#373447', meta:'Single · 2:39',
   q:'Djo End of Beginning', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/6e/df/af/6edfaf58-f901-e9b5-840b-9ac9e37f34b7/mzaf_8465065510938624101.plus.aac.p.m4a'},
  {id:'beautiful-people', title:'Beautiful People', artist:'Ed Sheeran', collab:'Khalid',
   date:'Jul 12', year:'2019', bg:'#3b3c40', meta:'Single · 3:18',
   q:'Ed Sheeran Beautiful People Khalid', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/ee/18/89/ee188926-d676-0d85-b57e-93790f68c411/mzaf_5973313052079190433.plus.aac.p.m4a'},
  {id:'colors', title:'Colors', artist:'Black Pumas', collab:'',
   date:'Jun 21', year:'2019', bg:'#592922', meta:'Single · 4:07',
   q:'Black Pumas Colors', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/38/3a/4d/383a4da2-6532-ff04-3bb3-e480ea7b94db/mzaf_10418172481474599121.plus.aac.p.m4a'},
  {id:'i-dont-care', title:"I Don't Care", artist:'Ed Sheeran', collab:'Justin Bieber',
   date:'May 10', year:'2019', bg:'#423f3c', meta:'Single · 3:40',
   q:"Ed Sheeran I Don't Care Justin Bieber", ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/84/bb/fb/84bbfbcd-9f63-dfa0-8660-ff86ced2eaaa/mzaf_11693010840075646451.plus.aac.p.m4a'},
  {id:'pretender', title:'Pretender', artist:'Official髭男dism', collab:'',
   date:'Apr 17', year:'2019', bg:'#631829', meta:'Single · 5:26',
   q:'Official髭男dism Pretender', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/ce/0f/9c/ce0f9cf6-edfd-d964-317a-56781936a96b/mzaf_10158629645505453806.plus.aac.p.m4a'},
  {id:'perfect-duet', title:'Perfect Duet', artist:'Ed Sheeran', collab:'Beyoncé',
   date:'Dec 1', year:'2017', bg:'#15495c', meta:'Single · 4:20',
   q:'Ed Sheeran Perfect Duet Beyoncé', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/61/db/5e/61db5e84-5cfb-181e-fbb7-8248035b7ab1/mzaf_12510832498126033168.plus.aac.p.m4a'},
  {id:'castle-on-the-hill', title:'Castle on the Hill', artist:'Ed Sheeran', collab:'',
   date:'Jan 6', year:'2017', bg:'#155165', meta:'Single · 4:21',
   q:'Ed Sheeran Castle on the Hill', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/07/be/08/07be085d-6f06-8b4e-cea1-f40b4dca3815/mzaf_12958775594313934161.plus.aac.p.m4a'},
  {id:'locked-away', title:'Locked Away', artist:'R. City', collab:'Adam Levine',
   date:'Jun 29', year:'2015', bg:'#484132', meta:'Single · 3:47',
   q:'R. City Locked Away Adam Levine', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/f2/d5/d6/f2d5d634-483f-7e6f-3385-818d6ffbe91f/mzaf_13375317712317642570.plus.aac.p.m4a'},
  {id:'lost-stars', title:'Lost Stars', artist:'Adam Levine', collab:'',
   date:'Jun 23', year:'2014', bg:'#245c59', meta:'Single · 4:28',
   q:'Adam Levine Lost Stars Begin Again', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/b1/6b/3c/b16b3c77-ac12-55f6-c9ef-abe3a0548322/mzaf_13143599158828062444.plus.aac.p.m4a'},
  {id:'stay-with-me', title:'Stay With Me', artist:'Sam Smith', collab:'',
   date:'Apr 14', year:'2014', bg:'#403d3b', meta:'Single · 2:53',
   q:'Sam Smith Stay With Me', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/d8/90/ef/d890ef3d-95b8-2224-5ff2-4ed56a359449/mzaf_8285804271834164275.plus.aac.p.m4a'},
  {id:'only-love-can-hurt', title:'Only Love Can Hurt Like This', artist:'Paloma Faith', collab:'',
   date:'Mar 10', year:'2014', bg:'#4e2d34', meta:'Single · 3:53',
   q:'Paloma Faith Only Love Can Hurt Like This', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/e1/67/51/e167517f-d31f-ec28-10c2-dea246dde88e/mzaf_16290264548209879114.plus.aac.p.m4a'},
  {id:'vivir-mi-vida', title:'Vivir Mi Vida', artist:'Marc Anthony', collab:'',
   date:'Apr 26', year:'2013', bg:'#403d3b', meta:'Single · 4:12',
   q:'Marc Anthony Vivir Mi Vida', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/10/fd/bf/10fdbf20-d17d-a8a2-6058-c1ef9f221068/mzaf_9159790581568803090.plus.aac.p.m4a'},
  {id:'price-tag', title:'Price Tag', artist:'Jessie J', collab:'B.o.B',
   date:'Jan 25', year:'2011', bg:'#453c35', meta:'Single · 3:43',
   q:'Jessie J Price Tag', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/03/2f/30/032f3031-ca60-9967-b82c-1c9d2fb2b1c3/mzaf_7409978316038357876.plus.aac.p.m4a'},
  {id:'just-a-dream', title:'Just a Dream', artist:'Nelly', collab:'',
   date:'Aug 16', year:'2010', bg:'#592b21', meta:'Single · 3:58',
   q:'Nelly Just a Dream', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/ad/ef/f3/adeff3b1-8ca7-fe69-4404-d4574be0ed5d/mzaf_4818658649735952743.plus.aac.p.m4a'},
  {id:'last-night-on-earth', title:'Last Night on Earth', artist:'Green Day', collab:'',
   date:'May 15', year:'2009', bg:'#693811', meta:'Album track · 3:57',
   q:'Green Day Last Night on Earth', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview122/v4/fc/40/58/fc405830-973b-4f15-23c1-6325d840505e/mzaf_6611125790634989435.plus.aac.p.m4a'},
  {id:'21-guns', title:'21 Guns', artist:'Green Day', collab:'',
   date:'May 15', year:'2009', bg:'#693811', meta:'Single · 5:22',
   q:'Green Day 21 Guns', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview122/v4/7c/cc/4f/7ccc4f71-2f5c-6a49-d6e5-0c98c8d32e80/mzaf_9206916011381489115.plus.aac.p.m4a'},
  {id:'viva-la-vida', title:'Viva La Vida', artist:'Coldplay', collab:'',
   date:'May 25', year:'2008', bg:'#453b35', meta:'Single · 4:01',
   q:'Coldplay Viva La Vida', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview116/v4/2b/04/65/2b0465c3-2db1-e461-2362-14b528456b8f/mzaf_1805426141027060154.plus.aac.p.m4a'},
  {id:'fix-you', title:'Fix You', artist:'Coldplay', collab:'',
   date:'Jun 6', year:'2005', bg:'#114969', meta:'Single · 4:55',
   q:'Coldplay Fix You', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/e5/42/e3/e542e340-a45c-695e-e0b8-6155e222ebc0/mzaf_14955746616030397665.plus.aac.p.m4a'},
  {id:'boulevard', title:'Boulevard of Broken Dreams', artist:'Green Day', collab:'',
   date:'Sep 21', year:'2004', bg:'#53272a', meta:'Single · 4:21',
   q:'Green Day Boulevard of Broken Dreams', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/46/9a/fb/469afb85-6a00-c96d-c235-949baa7ce758/mzaf_8692192130778653752.plus.aac.p.m4a'},
  {id:'somewhere-only-we-know', title:'Somewhere Only We Know', artist:'Keane', collab:'',
   date:'May 10', year:'2004', bg:'#522a28', meta:'Single · 3:59',
   q:'Keane Somewhere Only We Know', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/fa/93/fe/fa93fec8-adc4-1398-447a-69aca2622c25/mzaf_13909236668081502666.plus.aac.p.m4a'},
  {id:'in-the-end', title:'In the End', artist:'Linkin Park', collab:'',
   date:'Oct 24', year:'2000', bg:'#423b38', meta:'Single · 3:36',
   q:'Linkin Park In the End', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/3f/cb/c7/3fcbc7cc-0606-7f6e-7fc3-793318cfd1ed/mzaf_16081918663584534594.plus.aac.p.m4a'},
  {id:'dont-look-back', title:"Don't Look Back in Anger", artist:'Oasis', collab:'',
   date:'Oct 2', year:'1995', bg:'#403e3b', meta:'Single · 4:50',
   q:'Oasis Dont Look Back in Anger', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/c1/a1/39/c1a13912-0258-e74a-18ec-01f3b75f9882/mzaf_7973906281407419040.plus.aac.p.m4a'},
  {id:'i-want-to-break-free', title:'I Want to Break Free', artist:'Queen', collab:'',
   date:'Feb 27', year:'1984', bg:'#423c38', meta:'Single · 3:21',
   q:'Queen I Want to Break Free', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview125/v4/9e/60/bc/9e60bc2a-ae27-cc54-9821-429e7d2e8541/mzaf_17496100486957198237.plus.aac.p.m4a'},
  {id:'too-much-heaven', title:'Too Much Heaven', artist:'Bee Gees', collab:'',
   date:'Oct 24', year:'1978', bg:'#5a2420', meta:'Single · 4:56',
   q:'Bee Gees Too Much Heaven', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/7c/00/d6/7c00d613-c377-d50f-2a6f-b969a68557eb/mzaf_3009144308125523567.plus.aac.p.m4a'},
  {id:'baby-come-back', title:'Baby Come Back', artist:'Player', collab:'',
   date:'Sep 1', year:'1977', bg:'#3c3941', meta:'Single · 4:16',
   q:'Player Baby Come Back', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview115/v4/57/22/1b/57221bb8-00f6-3d7f-2c38-7204e98c1dfb/mzaf_4332271055466605013.plus.aac.p.m4a'},
  {id:'bohemian-rhapsody', title:'Bohemian Rhapsody', artist:'Queen', collab:'',
   date:'Oct 31', year:'1975', bg:'#4a3930', meta:'Single · 5:54',
   q:'Queen Bohemian Rhapsody', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/35/5e/92/355e924d-728f-a25c-5e69-d8c53561658f/mzaf_3026523263970634353.plus.aac.p.m4a'},
  {id:'piano-man', title:'Piano Man', artist:'Billy Joel', collab:'',
   date:'Nov 9', year:'1973', bg:'#3d3d3e', meta:'Single · 5:39',
   q:'Billy Joel Piano Man', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview211/v4/8e/e4/51/8ee451b3-a74e-25fa-be4e-09ce04a39df0/mzaf_13595078232063121698.plus.aac.p.m4a'},
  {id:'country-roads', title:'Take Me Home, Country Roads', artist:'John Denver', collab:'',
   date:'Apr 6', year:'1971', bg:'#473734', meta:'Single · 3:14',
   q:'John Denver Take Me Home Country Roads', ptrack:null,
   preview:'https://audio-ssl.itunes.apple.com/itunes-assets/AudioPreview221/v4/e7/d1/c4/e7d1c476-fa55-0be0-adf8-5fdcc7d18f3f/mzaf_3863812668516994856.plus.aac.p.m4a'},
];

/* ================= 唱片內頁 =================
   mine 是留給你自己寫的那一欄。填了才會在內頁最底下出現，空著就自動隱藏。
   例：mine:"2024 年冬天在回家的公車上單曲循環了一個月。" */
const NOTES = {
'birds-of-a-feather':{
  hook:"她一度想把這首歌從專輯裡刪掉，因為它太快樂了。",
  story:"專輯《HIT ME HARD AND SOFT》從 2022 年底開工，兄妹倆坦承有很長一段時間毫無靈感。這首歌斷斷續續寫了近一年，Billie 說他們從沒有一首歌想得這麼久。她糾結整整一年要不要收錄，覺得曲調太明亮不像自己；FINNEAS 則把真實鳥鳴埋進編曲底層，笑說有點太直白但好聽。",
  meaning:"歌名取自英文諺語「物以類聚」。Billie 說坊間有太多為愛而死的情歌，她想把方向反過來：不是為你而死，是活著陪你到最後。內容是把整副身家壓上去的那種愛，明知過頭仍不收手，用近乎喊叫的音量說出承諾。明亮的合成器與拍手，和略帶偏執的告白形成她慣用的錯位。",
  writers:"Billie Eilish, FINNEAS O'Connell",
  source:"HIT ME HARD AND SOFT, 2024",
  note:"2024 年 Spotify 全球最多人聽的一首歌。",
  mine:""},
'beautiful-things':{
  hook:"越是握在手裡的東西，越怕哪天被收回去。",
  story:"2023 年秋天，剛搬到洛杉磯的 Benson Boone 某晚睡不著，走到客廳坐上外婆留下的舊鋼琴，摸出了主歌旋律。隔天進錄音室，他和 Jack LaFrantz、製作人 Evan Blair 第一天合作就錄了下來——原本是兩段各自寫的殘稿，LaFrantz 提議合成一首，後製又磨了兩週。發行前的社群預告就累積上億次觀看。",
  meaning:"這是一首關於「怕」的歌。Boone 說當時他剛進入一段感情，第一次感覺人生完全不在自己控制之中。歌裡的人數著手上的好東西——家人健在、愛人還在身邊——卻無法不去想這些哪天會被拿走。鋼琴主歌鋪陳感激，副歌突然拉滿嗓子的嘶吼，就是那份說不出口的恐慌。",
  writers:"Benson Boone, Jack LaFrantz, Evan Blair",
  source:"Fireworks & Rollerblades, 2024（單曲 2024 年 1 月先行）",
  note:"IFPI 認證 2024 年全球最暢銷單曲。",
  mine:""},
'end-of-beginning':{
  hook:"他離開芝加哥那年寫的歌，兩年後才被世界聽見。",
  story:"Joe Keery 因《Stranger Things》走紅後從芝加哥搬到洛杉磯，這首歌是他回望那段大學與樂團生活的產物——他在 DePaul 唸戲劇、待過 Post Animal。2022 年 4 月他先在阿拉巴馬州的演出上首唱，同年 9 月收進獨立發行的專輯《DECIDE》，與 Adam Thein 共同製作。當時幾乎沒有人注意到它。",
  meaning:"Keery 說這首歌是回頭看二十出頭那幾年，既想念、又對發生過的事心存感激。芝加哥在歌裡不只是地名，是一個已經離開、卻反覆在夢裡回去的階段。歌名本身就是矛盾：某件事結束的同一刻，另一件事開始。合成器與吉他堆出的懷舊聲響，比歌詞更像記憶運作的方式。",
  writers:"Joe Keery（製作 Joe Keery, Adam Thein）",
  source:"DECIDE, 2022（2024 年 3 月才正式發行為單曲）",
  note:"2026 年初《Stranger Things》完結後才登上英國榜冠軍。",
  mine:""},
'beautiful-people':{
  hook:"在全世界最盛產「美麗的人」的城市，寫一首拒絕變成那種人的歌。",
  story:"同樣收在 2019 年《No.6 Collaborations Project》，Ed Sheeran 找上 Khalid 對唱，與 Max Martin、Shellback、Fred Gibson 共同創作。場景整個設在洛杉磯——比佛利山、Rodeo Drive、藍寶堅尼與濾鏡完美的生活。兩個早已身在名利場中心的歌手，選擇從內部唱一首質疑名利場的歌。",
  meaning:"被一群「美麗的人」包圍——他們開名車、辦派對、把日子活成 Instagram——敘事者卻一再強調：我們不屬於這裡，因為我們只想當自己。它把「不合群」寫成一種驕傲：在人人都想被羨慕的地方，選擇平凡與真實，和身邊的人守住那個不必被包裝的自己。",
  writers:"Ed Sheeran, Khalid, Max Martin, Shellback, Fred Gibson",
  source:"No.6 Collaborations Project, 2019（單曲 2019 年 7 月）",
  note:"一首從名利場內部唱出的反名利場情歌。",
  mine:""},
'colors':{
  hook:"在叔叔家的屋頂午睡醒來，就著天色一個音一個音摸出來。",
  story:"Eric Burton 說這首歌來自他剛學會彈吉他的時候：某天在新墨西哥州叔叔家的屋頂午睡醒來，就著天色一個音一個音摸出來。當時他在教會帶敬拜，想寫一個有信仰的人怎麼找到自己的真理——副歌那層福音式和聲就是這麼來的。後來他從聖塔莫尼卡碼頭一路唱到德州 Austin 街頭，2017 年遇上吉他手 Adrian Quesada，才有了現在的版本。",
  meaning:"Burton 的靈感是天空層層疊疊的顏色。整首歌反覆回到色彩這個意象，說的是人與人的差異可以並存——膚色、來歷、信念都屬於同一片天。底下同時流著對生死的意識：正因為日子有限，眼前這些顏色才值得停下來看。復古靈魂樂的編制加上福音合聲，把它撐得近似一首讚美詩。",
  writers:"Eric Burton（製作 Adrian Quesada）",
  source:"Black Pumas, 2019（單曲 2019 年 4 月）",
  note:"入圍 2021 年葛萊美年度最佳唱片。",
  mine:""},
'i-dont-care':{
  hook:"地表最紅的兩個人，合寫了一首關於在派對上渾身不對勁的歌。",
  story:"這是 2019 年 Ed Sheeran 沉潛一年後的回歸單曲，找來 Justin Bieber 對唱，與瑞典金牌製作 Max Martin、Shellback 等人共同完成。兩人都不只一次公開談過自己的社交焦慮——站在滿是名人的場合裡格格不入、只想離開。這份共同的不自在，成了整首歌的起點。5 月 10 日發行，是《No.6 Collaborations Project》的先行曲。",
  meaning:"在一個到處都是陌生人、燈光太亮、笑容太假的場合，敘事者渾身不對勁，唯一的浮木是身邊那個人。歌名那句「我不在乎」不是叛逆，是依賴：只要你在，這場我本來想逃的派對就撐得下去。明快的節拍底下，其實是兩個大明星承認自己也會怕。",
  writers:"Ed Sheeran, Justin Bieber, Max Martin, Shellback, Fred Gibson, Jason Boyd",
  source:"No.6 Collaborations Project, 2019",
  note:"空降英國排行榜冠軍。",
  mine:""},
'pretender':{
  hook:"在夢裡發現這是夢，卻還不想醒過來。",
  story:"這是 Official髭男dism 第一次擔綱電影主題歌。從《コンフィデンスマンJP -ロマンス編-》還在劇本階段，團員就與製作團隊反覆討論，期間寫了不少備選曲；片方希望「在朗朗上口之中帶一點苦味」。作詞作曲的藤原聡說，沒遇上這部作品就不會有這首歌。假標題原本叫「Goodbye Romance」，歌詞裡的「世界線」與封面的輝光管，都來自動畫《Steins;Gate》。",
  meaning:"歌名指「假裝的人」。敘事者站在喜歡的人身邊，關係卻始終停在朋友那一格；他清楚知道對方不是自己的命定之人，卻仍不肯結束這場自欺。樂團形容那是在夢裡意識到這是夢、卻還想繼續當主角的寂寞。副歌轉調、真假音頻繁切換，把說不出口的克制推到臨界點。",
  writers:"藤原聡（作詞・作曲）／編曲 Official髭男dism",
  source:"單曲 Pretender, 2019；收錄於《Traveler》, 2019",
  note:"2025 年 5 月累積串流突破 10 億次。",
  mine:""},
'perfect-duet':{
  hook:"他想寫一首比〈Thinking Out Loud〉更好的情歌，然後找了地表最強的聲音來合唱。",
  story:"〈Perfect〉出自 2017 年專輯《÷》，Ed Sheeran 寫給青梅竹馬、後來成為妻子的 Cherry Seaborn——兩人是中學同學，多年後在紐約重逢相戀。他說寫這首時是刻意要超越自己的〈Thinking Out Loud〉。原曲走紅後他一直想做一個對唱版，心裡的第一人選就是 Beyoncé；她答應了，錄下女聲視角的段落，兩人一來一往。對唱版在 2017 年 12 月 1 日發行。",
  meaning:"一首毫不遮掩的定情歌：赤腳在草地上跳舞、在黑暗中相擁，找到一個「比我認識的任何人都堅強」的人。獨唱版是一個人對著世界立誓；對唱版把同一段誓言拆成兩個聲音各自應答——他唱他找到的女人，她唱她找到的男人，承諾於是有了回聲。",
  writers:"Ed Sheeran",
  source:"÷ (Divide), 2017（對唱版單曲 2017 年 12 月）",
  note:"推動〈Perfect〉成為 2017 年英國耶誕冠軍單曲。",
  mine:""},
'castle-on-the-hill':{
  hook:"他說沒人替 Suffolk 寫過情歌，所以他自己寫了一首。",
  story:"歌名裡的城堡是 Framlingham Castle，Ed Sheeran 十七歲離家前住的 Suffolk 小鎮地標。2015 年他和 Benny Blanco 一起寫下這首歌，音樂上的參照是 Snow Patrol 的《Fallen Empires》，他想做出類似 Bruce Springsteen〈The River〉那種回望青春的質地。2017 年 1 月 6 日與〈Shape of You〉同日發行，MV 回到他母校 Thomas Mills High School 取景。",
  meaning:"一封寫給故鄉的信。歌裡是十幾歲的碎片——摔斷腿的牆頭、第一次抽菸、飆太快的鄉間公路、放學後和朋友鬼混的傍晚——然後鏡頭切到現在：當年那群人早已散開，有人結婚、有人過得不好，有人再也回不來。Sheeran 說家鄉有很多正面的東西，但也有很多悲傷。",
  writers:"Ed Sheeran, Benny Blanco",
  source:"÷ (Divide), 2017",
  note:"歌中飆車的描述，讓 Suffolk 警方公開呼籲別超速。",
  mine:""},
'locked-away':{
  hook:"寫給那個在父親坐牢五年裡沒走的母親。",
  story:"R. City 是美屬維京群島的 Thomas 兄弟，出道前已替 Rihanna、Miley Cyrus 寫過暢銷曲。這首歌寫的是自家往事：父親入獄五年，出獄後當清潔工、也染過毒癮，母親始終沒走，兩人結褵近四十年。製作人 Dr. Luke 剛做完 Maroon 5 的〈Sugar〉，牽線找上 Adam Levine，他聽完兩首 demo 都點頭，兄弟倆自己挑了這首。",
  meaning:"整首歌是一串假設性的提問：如果我一無所有、如果我被關起來、如果我失去所有光環，你還會在嗎。它把愛情丟進最不浪漫的場景裡檢驗——不是花前月下，而是探監室與空皮夾。Adam Levine 的副歌唱得近乎懇求，而真正的答案藏在兄弟倆母親的選擇裡：留下來本身就是回答。",
  writers:"Theron Thomas, Timothy Thomas, Dr. Luke, Cirkut, Toni Tennille",
  source:"What Dreams Are Made Of, 2015",
  note:"旋律取自 Captain & Tennille 1980 年冠軍曲，Toni Tennille 因此掛名。",
  mine:""},
'lost-stars':{
  hook:"同一首歌，電影裡出現兩次：一次赤誠，一次被製作人包裝到面目全非。",
  story:"來自 John Carney（《曾經．愛是唯一》導演）2014 年的電影《Begin Again》。詞曲主筆是 New Radicals 的 Gregg Alexander，與 Danielle Brisebois 等人合寫。片中 Adam Levine 飾演一夕成名、逐漸迷失的搖滾歌手 Dave——這是 Maroon 5 主唱的大銀幕處女作；同一首〈Lost Stars〉在戲裡出現兩個版本，一個是女主角清唱的素樸原貌，一個是 Dave 被唱片工業重編成體育館規格的華麗版本，兩相對照就是整部電影的命題。",
  meaning:"一連串對著夜空的發問：我們是不是都是想把黑暗點亮、卻終將迷航的星？歌裡的人追著名聲與愛跑，一邊追一邊懷疑這一切到底算不算數。它把「渴望被看見」寫成一種近乎天真的脆弱——星星再亮，也不知道有沒有人在看。",
  writers:"Gregg Alexander, Danielle Brisebois, Nick Lashley, Nick Southwood",
  source:"Begin Again 電影原聲帶, 2014",
  note:"入圍第 87 屆奧斯卡最佳原創歌曲，敗給《Selma》的〈Glory〉。",
  mine:""},
'stay-with-me':{
  hook:"三十分鐘寫完的一夜情，版權卻談了大半年。",
  story:"在倫敦 Old Street 的錄音室，Jimmy Napes 丟出「Stay With Me」這句話，Sam Smith 立刻想到一夜情隔天的空房間。Phillips 彈鋼琴、Napes 打鼓，三人三、四十分鐘就寫完。隔年 Tom Petty 的版權方指出副歌與〈I Won't Back Down〉相似，三人承認雷同卻堅稱沒聽過原曲，2015 年協議讓 Petty 與 Jeff Lynne 掛名並分 12.5% 版稅。",
  meaning:"這是一首關於清晨四點的歌。對方準備離開，說話者明知這只是一夜的關係，仍開口請對方留下——不是因為愛，而是不想獨自面對接下來的沉默。Sam Smith 把整張《In the Lonely Hour》寫給一個不愛他的人，這首是其中最赤裸的一刻：福音式的合唱堆得越滿，越顯得那個房間空。",
  writers:"Sam Smith, Jimmy Napes, Tourist；後追加 Tom Petty, Jeff Lynne",
  source:"In the Lonely Hour, 2014",
  note:"奪下 2015 年葛萊美年度製作與年度歌曲。",
  mine:""},
'only-love-can-hurt':{
  hook:"她原本拒唱這首歌，因為上面沒有她的名字。",
  story:"詞曲全出自 Diane Warren——寫過〈I Don't Want to Miss a Thing〉的美國金牌寫手。Paloma Faith 起初拒唱，理由很直接：沒有她的作者掛名。真正聽完之後她改口，說歌詞幾乎寫中她當時的感情狀態。成品走 Motown 六〇年代路線，以銅管和鼓打底，直到最後幾段副歌才把弦樂大量堆上來。",
  meaning:"講的是失戀之後那種無處可躲的痛：說話者知道對方不會回來，卻仍在原地重播每個細節，並承認世上沒有別的東西傷得這麼深。有趣的是編曲並不悲——鼓點是可以跳舞的。Paloma Faith 說過，這首歌在派對響起時，大家反而覺得「是難過沒錯，但管他的，跳吧」。",
  writers:"Diane Warren",
  source:"A Perfect Contradiction, 2014",
  note:"英國第六名，她個人最佳；2022 年因短影音二度翻紅。",
  mine:""},
'vivir-mi-vida':{
  hook:"阿爾及利亞的舞曲，在邁阿密被拆掉重組成騷莎。",
  story:"原曲是 Khaled 2012 年的〈C'est la vie〉，RedOne 製作，在歐洲與中東紅過一輪的電子舞曲。Marc Anthony 找回老搭檔 Sergio George，在邁阿密 Hit Factory Criteria 重錄，把電子節拍換成 clave 與銅管，改寫成西班牙文騷莎。收在 2013 年專輯《3.0》，也是兩人睽違多年的再度聯手。",
  meaning:"歌名直譯是「活我的人生」，主張很簡單：痛苦會來，日子照樣笑著過。它像一份給挫折的回應清單——不逃避、不假裝沒事，但拒絕被留在原地。Marc Anthony 事後形容，是這首歌讓他重新拿回自信；它後來也成了整個拉丁世界的宴會國歌。",
  writers:"Khaled, RedOne, Bilal Hajji 等；西語版改編 Marc Anthony",
  source:"3.0, 2013",
  note:"2013 年拉丁葛萊美年度製作，Hot Latin Songs 冠軍。",
  mine:""},
'price-tag':{
  hook:"剛簽進唱片公司的新人，寫了一首嫌錢太吵的歌。",
  story:"Jessie J 和 Claude Kelly、Dr. Luke 合寫這首歌時，距離他們替 Miley Cyrus 做完〈Party in the U.S.A.〉才四個月。她剛踏進音樂工業，感覺人人戴著墨鏡談生意、一切由錢說了算，就把這股不耐寫成歌。B.o.B 的饒舌她堅持面對面錄，為此四天內飛了五趟。",
  meaning:"表面上是一首反物質主義的派對歌：別管標價，回到音樂本身。但 Jessie J 說過，它其實也在講唱片工業——新人在公司眼裡是一組數字、一份業績，跟才華或真誠無關。她也承認自己得靠賣歌維生，並不是要人別花錢，只是不希望所有事都被換算成金額。",
  writers:"Jessie J, Dr. Luke, Claude Kelly, B.o.B",
  source:"Who You Are, 2011",
  note:"英國空降冠軍，全球銷量逾三百萬。",
  mine:""},
'just-a-dream':{
  hook:"大家都猜這是寫給 Ashanti 的分手信，他說不是。",
  story:"2010 年 Nelly 和長期搭檔 Rico Love 在邁阿密的 Hit Factory 與 Playland Playhouse 完成這首歌，Jim Jonsin 與 Rico Love 共同製作，吉他手 Frank Romano 也掛名作者。外界普遍認定是寫給前女友 Ashanti，Nelly 公開否認，說那只是兩人想出來的歌，而且刻意寫得誰都能對號入座——不分貧富、年紀或膚色。",
  meaning:"敘事者從夢裡醒來，發現那段感情真的結束，只剩自己在腦中重播。重點不在誰對誰錯，而在「當時應該再多做一點」的懊悔——失去之後才看清價值的那種滯後。Nelly 形容它談的是愛過、弄丟，然後才明白該更用力抓住，也是他從嘻哈轉向流行抒情的一次成功嘗試。",
  writers:"Nelly, Rico Love, Jim Jonsin, Frank Romano",
  source:"5.0, 2010",
  note:"Billboard Hot 100 第三名，是他〈Grillz〉後最高名次。",
  mine:""},
'last-night-on-earth':{
  hook:"他第一次用假音唱歌，只為了寫給一個人聽。",
  story:"Billie Joe Armstrong 在錄製《21st Century Breakdown》之前才學會彈鋼琴，專輯裡不少歌就是坐在琴前寫出來的，這首是其中之一。他說這是寫給妻子 Adrienne 的情歌，是一個很私密的片刻，對象只有一個人。錄音時他第一次嘗試假音演唱，自己形容從沒這樣唱過。製作人 Butch Vig 把它放在概念專輯第一幕的收尾。",
  meaning:"核心是一句末日式的告白：就算失去所有東西，那份愛還是要送出去。在專輯敘事裡，這被安排成 Christian 寫給 Gloria 的一首詩，兩個角色在崩壞的美國裡互相攀住。編曲刻意放軟，鋼琴領路、人聲飄在上面，跟整張唱片的怒氣形成對照——它不是抗議歌，是在混亂中確認還有一個人值得留下來。",
  writers:"Billie Joe Armstrong, Green Day",
  source:"21st Century Breakdown, 2009（專輯曲，未發行單曲）",
  note:"2025 年 FireAid 賑災演唱會，Billie Eilish 上台合唱這首開場曲。",
  mine:""},
'21-guns':{
  hook:"為了副歌太像 Bowie，他們乾脆把 Bowie 掛進作者欄。",
  story:"收在《21st Century Breakdown》第三幕，Butch Vig 製作。Armstrong 說歌名來自為陣亡者鳴放的 21 響禮砲，只是用體育館搖滾的規格演出來。副歌旋律和 David Bowie 寫給 Mott the Hoople 的〈All the Young Dudes〉太接近，樂團索性把 Bowie 列為共同作者以避開官司。隔年百老匯音樂劇《American Idiot》收了這首，樂團還與原班卡司重錄一版。",
  meaning:"一個人被自己的憤怒打到彈盡援絕，開始問還要撐到什麼時候。Armstrong 說在音樂劇裡，這是主角意識到得收拾自己的轉折點。它把投降寫成一種倖存而不是失敗——放下武器不等於認輸，是承認再打下去只剩灰燼。禮砲的意象一邊悼念死者，一邊質問把人送去死的那套愛國修辭。",
  writers:"Billie Joe Armstrong, Green Day, David Bowie",
  source:"21st Century Breakdown, 2009",
  note:"Billboard Hot 100 最高第 22 名，2009 年 MTV VMA 拿下三座。",
  mine:""},
'viva-la-vida':{
  hook:"一幅 Frida Kahlo 的臨終畫作，借給了一首失位國王的歌。",
  story:"歌名來自 Chris Martin 在墨西哥 Frida Kahlo 故居看到的同名畫作——那是 Kahlo 病痛纏身、去世前不久畫的西瓜靜物。他說當下只覺得這標題真好，就記了下來。旋律是凌晨兩點左右冒出來的，十分鐘就有雛形，但進錄音室後前後試了約五十五個版本，直到找到教堂鐘聲的音色才拍板。製作人是 Brian Eno。",
  meaning:"敘事者是一個曾經呼風喚雨、如今掃著自己從前擁有的街道的統治者。外界常把他指認成 Louis XVI，Martin 從沒證實，那份模糊本身就是設計。他把這首講得相當正面：一個人承認犯過錯、接受懲罰，但沒把贖回的可能關死。革命鼓聲與教堂鐘聲之間，講的是權力散去之後，人還剩下什麼。",
  writers:"Guy Berryman, Jonny Buckland, Will Champion, Chris Martin",
  source:"Viva la Vida or Death and All His Friends, 2008",
  note:"英美單曲榜同時封王，2009 年拿下葛萊美年度歌曲。",
  mine:""},
'fix-you':{
  hook:"一台亡者留下的鍵盤，成了這首安慰生者的歌的骨架。",
  story:"2002 年 Gwyneth Paltrow 的父親、導演 Bruce Paltrow 過世，Chris Martin 是在那之後幾週認識她的。Bruce 生前買下的一台鍵盤留了下來，Martin 把它接上電源，找到一個像教堂管風琴卻又不是管風琴的音色，整首歌就從那裡長出來。他後來說這是 Coldplay 最重要的作品，幾乎是靠它撐過了很難的兩年。",
  meaning:"這是寫給喪親者的歌，不是寫給悲傷本身。前半段幾乎只有一層管風琴般的鍵盤和假音，像在病房裡壓低聲音說話；後半段鼓、弦樂與合唱一起壓進來，情緒才被允許放大。主題是有人在你什麼都修不好的時候仍願意陪你走回去——歌名說的「修好你」其實做不到，能做的只有不走開。",
  writers:"Guy Berryman, Jonny Buckland, Will Champion, Chris Martin",
  source:"X&Y, 2005",
  note:"英國榜最高第 4 名，2017 年 One Love Manchester 賑災演出曲目。",
  mine:""},
'boulevard':{
  hook:"派對散場之後，主角一個人走在陌生城市裡的宿醉。",
  story:"2003 年 Billie Joe Armstrong 暫住紐約 East Village，一個人在大城市裡寫下這首歌。他說那是關於孤獨，也關於怎麼從孤獨裡榨出一點力氣。製作人 Rob Cavallo 一聽 demo 就認定這是樂團沒做過的東西、而且會紅。在《American Idiot》的敘事裡它接在〈Holiday〉之後——前一首是狂歡，這首是隔天早上的宿醉。",
  meaning:"唱的是專輯主角 Jesus of Suburbia：一個自以為看透一切、逃離郊區奔向大城市的年輕人，到了現場才發現沒人在等他。歌裡那條路是他唯一認得的東西，影子是唯一的同行者。它把青春期的自我正義寫成了代價——不是反抗失敗的悲壯，而是更難堪的東西：孤獨，而且沒有觀眾。",
  writers:"Billie Joe Armstrong, Green Day",
  source:"American Idiot, 2004",
  note:"2006 年葛萊美年度製作，現代搖滾榜蟬聯 16 週冠軍。",
  mine:""},
'somewhere-only-we-know':{
  hook:"一片東薩塞克斯的樹林，被寫成所有人的避難所。",
  story:"2001 年吉他手 Dominic Scott 離團，Keane 索性不補人，把 Tim Rice-Oxley 的鋼琴推到前面當主奏樂器——這首 demo 就寫在那段時期。歌裡的地景是真的：Rice-Oxley 老家附近、East Sussex 的 Battle 一帶，一棵倒下的松樹和一條小路，是他們十二歲踢球的地方。2004 年作為首張專輯的首支單曲發行。",
  meaning:"表面是回到一個只有「我們」知道的地方，實際上那地方一半真實、一半是記憶重建的。Rice-Oxley 刻意留白，說它可以是一段好回憶、一個偏愛的角落，任何人都能填進自己的版本；鼓手 Richard Hughes 也說每個人聽到的都不一樣。真正的動力不是懷舊，是眼前的日子講不通了，所以想找一個講得通的地方。",
  writers:"Tim Rice-Oxley, Tom Chaplin, Richard Hughes",
  source:"Hopes and Fears, 2004",
  note:"2013 年 Lily Allen 為 John Lewis 耶誕廣告翻唱，登上英國榜冠軍。",
  mine:""},
'in-the-end':{
  hook:"主唱討厭它、不想收進專輯——後來它成了樂團的名片。",
  story:"Mike Shinoda 在好萊塢一間沒有窗戶的排練室裡熬夜寫出來，那個鋼琴動機是當晚磨出來的。他認為這首能一次展示樂團的所有面向：旋律、饒舌、節拍、搖滾與嘶吼。Chester Bennington 是唱反調的那一個，不只不喜歡，還主張別收進《Hybrid Theory》、更別發單曲；製作人 Don Gilmore 堅持留下。後來 Bennington 承認自己看走眼。",
  meaning:"兩種聲音在同一首歌裡拉扯：Shinoda 的段落是懊悔與自我厭惡的獨白，Bennington 的副歌把它推成一句更大的控訴——用盡全力，最後仍然不算數。Shinoda 說這首真正在講的是與絕望角力，以及時間和生命有多短暫；他強調那是困惑，不是虛無。它替千禧年前後整整一代青少年的無處安放找到了聲音。",
  writers:"Chester Bennington, Rob Bourdon, Brad Delson, Joe Hahn, Mike Shinoda",
  source:"Hybrid Theory, 2000",
  note:"首支破 10 億 Spotify 串流的 nu-metal 歌曲，RIAA 鑽石認證。",
  mine:""},
'dont-look-back':{
  hook:"一首寫給不後悔的人的歌，後來成了整座城市的鎮定劑。",
  story:"Noel Gallagher 記得是在巴黎一個下雨的夜晚寫的，當晚 Oasis 剛在一間俱樂部演出完，回到旅館還只是個沒沒無聞的小團。副歌開頭那句是 Liam 在 Sheffield Arena 試音時隨口喊出來的，Noel 一聽就知道對了。歌詞裡還挪用了他手上那卷 John Lennon 私人錄音帶裡的一段話。這也是 Oasis 第一支由 Noel 而非 Liam 主唱的單曲。",
  meaning:"歌裡的 Sally 沒有原型，Noel 說只是個唸起來順的名字。他形容這是一首帶著倔強的歌：一個人回頭看自己的人生一頁頁翻過去，看見錯過與遺憾，卻決定舉杯而不是清算。Noel 自己也講不清它到底在說什麼，只說那首歌不太像是他寫出來的。2017 年之後，這份不帶恨意的釋然被整座曼徹斯特接了過去。",
  writers:"Noel Gallagher",
  source:"(What's the Story) Morning Glory?, 1995（單曲 1996）",
  note:"1996 年英國單曲榜冠軍，英國認證七白金。",
  mine:""},
'i-want-to-break-free':{
  hook:"貝斯手寫的歌，主唱穿上假髮推吸塵器，美國從此關上了門。",
  story:"這首歌出自貝斯手 John Deacon 之手——Queen 四個人都寫歌，這首和〈Another One Bites the Dust〉都掛他的名字。真正掀起風波的是 David Mallet 執導的 MV：四人反串英國肥皂劇《Coronation Street》的角色，在英國被當成喜劇傳統，MTV 卻幾乎不播。片中另有一段芭蕾，由皇家芭蕾舞團的 Wayne Eagling 編舞，Freddie Mercury 為此剃掉了招牌鬍子。",
  meaning:"表面上是一個人下定決心離開一段耗盡自己的關係，把話說得毫不留戀。但歌詞刻意寫得夠寬，任何形式的束縛都能套進去——這也是它後來在南非、南美被當成反壓迫歌曲傳唱的原因。寫的是私人的解脫，聽的人卻聽見了政治的解脫。",
  writers:"John Deacon",
  source:"The Works, 1984",
  note:"英國榜第 3，美國只到第 45——MTV 拒播是主因。",
  mine:""},
'too-much-heaven':{
  hook:"二十七個人聲堆出來的情歌，版稅一分不留，全給了 UNICEF。",
  story:"1978 年夏天，Bee Gees 在紐約聯合國總部開了記者會，宣布這首單曲的全部出版版稅捐給 UNICEF，作為他們對國際兒童年的獻禮。歌在同年七月錄於邁阿密的 Criteria Studios，是《Spirits Having Flown》整張裡錄得最久的一首：三部和聲疊了九層、等於二十七個人聲，再請來 Chicago 的銅管組。隔年一月他們在 Music for UNICEF 演唱會上唱了它。",
  meaning:"一首把愛情講得近乎虔誠的歌：擁有一個人的感覺太滿，滿到讓人覺得自己不配、覺得這份幸福是偷來的。Bee Gees 用假聲把那種暈眩感一直撐在半空中，不落地、也不激動。放進捐給孩子的脈絡裡，那份「得到太多」的心虛又多了一層意思。",
  writers:"Barry Gibb, Robin Gibb, Maurice Gibb",
  source:"Spirits Having Flown, 1979（單曲 1978）",
  note:"為 UNICEF 募得逾七百萬美元版稅，美加雙冠軍。",
  mine:""},
'baby-come-back':{
  hook:"兩個人各自剛被甩，坐下來把同一種悔意寫成同一首歌。",
  story:"Player 的兩位創團成員 Peter Beckett 與 J.C. Crowley 在差不多的時候各自結束了一段感情——Beckett 剛和交往五年的女友分手——兩人把手上的情緒湊在一起，寫成了這首歌。製作由 Dennis Lambert 與 Brian Potter 操刀，做成介於 soft rock 與 blue-eyed soul 之間的質地，成為樂團首張同名專輯的主打單曲。",
  meaning:"敘事者把錯全攬在自己身上，不辯解也不怪罪對方，只是一次又一次地請她回來。歌裡沒有戲劇性的大懺悔，就是一個人在夜裡把同一句話說了又說——那種明知道沒用還是要說出口的執拗，比激烈的挽留更接近真實的分手現場。",
  writers:"J.C. Crowley, Peter Beckett",
  source:"Player, 1977",
  note:"1978 年 1 月連三週登上 Billboard Hot 100 冠軍。",
  mine:""},
'bohemian-rhapsody':{
  hook:"一百八十次疊錄，八代母帶，和一個作者到死都沒解釋的謎。",
  story:"Freddie Mercury 進錄音室前就把整首歌在腦中排完了，錄音全程由他指揮。工程從 Rockfield Studios 起頭，前後動用五間錄音室、約三週完成；光歌劇段就疊了一百八十次錄音，母帶反覆併軌到第八代，磁帶被磨到近乎透明。唱片公司嫌近六分鐘的長度不可能當單曲，樂團索性繞過他們，把試聽帶直接交到電台 DJ 手上。",
  meaning:"三段不同的歌拼成的假歌劇：一個年輕人向母親坦白自己殺了人，接著被拖進一場荒誕的審判與討價還價，最後在硬搖滾裡把一切甩開。Mercury 一輩子沒說過它到底在講什麼，只說這首歌有很強的幻想色彩，聽的人自己去想就好。於是它同時被讀成告解、出櫃宣言，或什麼都不是。",
  writers:"Freddie Mercury",
  source:"A Night at the Opera, 1975",
  note:"英國榜連九週冠軍；2018 年成 20 世紀最多串流歌曲。",
  mine:""},
'piano-man':{
  hook:"他化名 Bill Martin 躲合約，順手把酒吧裡的每個人寫了進去。",
  story:"1971 年簽下的一紙合約幾乎綁走了 Billy Joel 的整個音樂人生，他躲到洛杉磯，用中間名化名 Bill Martin，在 Wilshire 區一家叫 The Executive Room 的鋼琴酒吧彈了大約半年的琴。歌裡的人都有原型：吧台的酒保、自稱在寫小說的房仲、海軍出身的常客，還有一位女侍——她後來成了他的第一任妻子 Elizabeth Weber。",
  meaning:"一個週六晚上的酒吧速寫。坐在吧台前的每個人都覺得自己本來可以成為別的樣子，而彈琴的那個人也是其中之一——他們用酒精和幾首熟悉的曲子，換一小時不必面對現實的權利。這首歌的溫柔在於它不評判任何人，只是把他們並排放著，然後繼續彈下去。",
  writers:"Billy Joel",
  source:"Piano Man, 1973",
  note:"只到告示牌第 25 名，Joel 說走紅時他很難為情。",
  mine:""},
'country-roads':{
  hook:"寫這首西維吉尼亞頌歌的人，當時從沒去過西維吉尼亞。",
  story:"1970 年，Bill Danoff 與 Taffy Nivert 開車去馬里蘭州 Gaithersburg 參加家族聚會，路上經過 Clopper Road，他在副駕抱著吉他哼出副歌。原本想寫麻州，嫌名字不夠上口，改成當時他根本沒去過的 West Virginia。年底 John Denver 在華府 Cellar Door 演出，左拇指剛撞斷，仍到兩人公寓聽了這首只有一段主歌和副歌的半成品，當場要了下來；三人熬到清晨六點改詞，隔晚 Denver 把歌詞貼在麥克風架上首唱。",
  meaning:"這是一首關於歸屬的歌：山、河與礦區生活拼出一個叫人非回去不可的家鄉，敘事者聽見的是路在召喚。只是那個故鄉更像想像的合成品——連地理都對不太準：Blue Ridge 山脈與 Shenandoah 河只在西維吉尼亞東端的 Jefferson 郡擦過約九英里。也正因為它不綁定某個真實座標，全世界都能把自己的故鄉填進去。",
  writers:"Bill Danoff, Taffy Nivert, John Denver",
  source:"Poems, Prayers & Promises, 1971",
  note:"2014 年獲列為西維吉尼亞官方州歌；Billboard 最高第 2 名。",
  mine:""},
};
